version: '3'
services:
  jenkins:
    build: .
    image: jenkins-sl-db
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home